- name: Set the system timezone
  hosts: all
  become: yes
  user: root

  vars_files:
    - env.yml

  tasks:
    - name: Set timezone
      ansible.builtin.command:
        cmd: timedatectl set-timezone {{ TIMEZONE }}

    - name: Create a new file with custom content
      ansible.builtin.copy:
        dest: /etc/cloud/cloud.cfg.d/99-unenabled-network.cfg
        content: |
          network: {config: disabled}
        owner: root
        group: root
        mode: '0644'

    - name: Apply Netplan configuration
      ansible.builtin.command:
        cmd: sudo netplan apply
      when: netplan_changed | default(false)

    - name: Enable and start SSH service
      ansible.builtin.service:
        name: ssh
        enabled: yes
        state: started

    - name: Update /etc/hosts on all nodes
      hosts: all
      become: yes
      vars:
        host_entries:
          - "postgres_node01_primary 192.168.208.106"
          - "postgres_node03_standby 192.168.208.107"
          - "postgres_node04_standby 192.168.208.108"
          - "ha_proxy_postgres 192.168.208.109"
          - "keep_alived_postgres 192.168.208.110"
    