- name: Set the system timezone
  hosts: all
  become: yes
  user: root

  vars_files:
    - env.yml

  tasks:
    - name: Set timezone
      ansible.builtin.command:
        cmd: timedatectl set-timezone {{ TIMEZONE }}

    - name: Create a new file with custom content
      ansible.builtin.copy:
        dest: /etc/cloud/cloud.cfg.d/99-unenabled-network.cfg
        content: |
          network: {config: disabled}
        owner: root
        group: root
        mode: '0644'

    - name: Apply Netplan configuration
      ansible.builtin.command:
        cmd: sudo netplan apply
      when: netplan_changed | default(false)

    - name: Enable and start SSH service
      ansible.builtin.service:
        name: ssh
        enabled: yes
        state: started

    # - name: Add PostgreSQL cluster entries to /etc/hosts
    #   ansible.builtin.blockinfile:
    #     path: /etc/hosts
    #     block: |
    #       # PostgreSQL Cluster Nodes
    #       - "postgres_node01_primary 192.168.208.106"
    #       - "postgres_node03_standby 192.168.208.107"
    #       - "postgres_node04_standby 192.168.208.108"
    #       - "ha_proxy_postgres 192.168.208.109"
    #       - "keep_alived_postgres 192.168.208.1"
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK - POSTGRESQL CLUSTER"
    #     insertafter: EOF
    #     owner: root
    #     group: root
    #     mode: '0644'
    - name: Remove old format entries
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '^\s*-\s*"(.*?)"\s*$'
        replace: '\1'
        
    - name: Add correct format entries
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          # PostgreSQL Cluster Nodes
          postgres_node01_primary 192.168.208.106
          postgres_node03_standby 192.168.208.107
          postgres_node04_standby 192.168.208.108
          ha_proxy_postgres 192.168.208.109
          keep_alived_postgres 192.168.208.110
        marker: "# {mark} ANSIBLE MANAGED BLOCK - POSTGRESQL CLUSTER"
        insertafter: EOF
    