---
- name: Install Apache Maven 3.9.9 on Ubuntu 22.04
  hosts: all
  become: true

  vars:
    maven_version: "3.9.9"
    maven_install_dir: "/opt/maven"
    maven_download_url: "https://downloads.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    jar_url: "https://drive.google.com/file/d/1SxdpKfdredxKe2piD2BszIiHPplzA-Sz/view?usp=sharing"
    jar_name: "sample-0.0.1-SNAPSHOT.jar" 
    install_dir: "/opt/myapp"
    java_opts: "-Xmx512m"
    mysql_root_password: "root"
    mysql_db_name: "demo"
    mysql_user: "root"
    mysql_user_password: "root"
    sql_file: "files/script.sql"  

    mysql_version: "8.0.2"
    sql_import_file: "/tmp/data.sql"

  tasks:        
    - name: Install curl and ca-certificates
      apt:
        name:
          - curl
          - ca-certificates
          - openjdk-21-jre
        state: present
        update_cache: yes

    - name: Create Maven install directory
      file:
        path: "{{ maven_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download Maven
      get_url:
        url: "{{ maven_download_url }}"
        dest: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
        mode: '0644'

    - name: Extract Maven archive
      unarchive:
        src: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: "{{ maven_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set environment variables for Maven
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export M2_HOME={{ maven_install_dir }}
          export PATH=$M2_HOME/bin:$PATH
        mode: '0755'

    - name: Source maven.sh immediately (optional)
      shell: source /etc/profile.d/maven.sh
      args:
        executable: /bin/bash
      changed_when: false

    - name: Create installation directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: directory
        mode: '0755'


    - name: Cài các gói phụ thuộc
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - gnupg
        - lsb-release
      when: ansible_os_family == "Debian"





    - name: Thêm repo MySQL chính thức
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/debian/ {{ ansible_distribution_release }} mysql-8.0"
        state: present
      when: ansible_os_family == "Debian"

    - name: Tải MySQL 8.0.2 cụ thể
      apt:
        name: mysql-server=8.0.2-1debian9
        state: present
      when: ansible_os_family == "Debian"

    - name: Đảm bảo dịch vụ MySQL đang chạy
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Đặt mật khẩu root cho MySQL
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Sao chép file SQL lên server
      copy:
        src: files/data.sql
        dest: "{{ sql_import_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: Import file SQL vào MySQL
      shell: |
        mysql -u root -p"{{ mysql_root_password }}" < {{ sql_import_file }}
      args:
        executable: /bin/bash







    - name: Download JAR file from Google Drive
      ansible.builtin.get_url:
        url: "{{ jar_url }}"
        dest: "{{ install_dir }}/{{ jar_name }}"
        mode: '0644'
      register: downloaded_jar

    - name: Install Java (nếu chưa có)
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_facts['pkg_mgr'] == 'apt'

    - name: Run JAR in background with nohup
      ansible.builtin.command: |
        nohup java {{ java_opts }} -jar {{ install_dir }}/{{ jar_name }} > {{ install_dir }}/app.log 2>&1 &
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/app.log"  
      when: downloaded_jar.changed 
