---
- name: Install Maven 3.9.9 and JRE 21 on Ubuntu
  hosts: all
  become: yes
  vars:
    maven_version: "3.9.9"
    maven_install_dir: "/opt/maven"
    maven_url: "https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
  
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    # Install required system packages
    - name: Install required system packages
      apt:
        name:
          - wget
          - tar
          - gzip
        state: present

    # Install OpenJDK 21 JRE
    - name: Add OpenJDK 21 repository
      apt_repository:
        repo: "deb https://pkgs.org/download/openjdk-21-jre {{ ansible_distribution_release }} main"
        state: present
        filename: "openjdk-21-jre"
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install OpenJDK 21 JRE
      apt:
        name: openjdk-21-jre
        state: present

    # Download and install Maven
    - name: Create Maven installation directory
      file:
        path: "{{ maven_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download Maven
      get_url:
        url: "{{ maven_url }}"
        dest: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
        checksum: "sha512:https://downloads.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz.sha512"
        timeout: 60

    - name: Extract Maven
      unarchive:
        src: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: "{{ maven_install_dir }}"
        remote_src: yes
        extra_opts: ["--strip-components=1"]
        creates: "{{ maven_install_dir }}/bin/mvn"

    # Set environment variables
    - name: Add Maven to system profile
      blockinfile:
        path: /etc/profile.d/maven.sh
        block: |
          export M2_HOME={{ maven_install_dir }}
          export MAVEN_HOME={{ maven_install_dir }}
          export PATH=${M2_HOME}/bin:${PATH}
        create: yes
        mode: '0644'

    - name: Update alternatives for Maven
      alternatives:
        name: mvn
        path: "{{ maven_install_dir }}/bin/mvn"
        priority: 100

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false
      ignore_errors: yes

    - name: Display Java version
      debug:
        msg: "{{ java_version.stderr }}"

    - name: Verify Maven installation
      command: mvn -version
      register: maven_version
      changed_when: false
      ignore_errors: yes

    - name: Display Maven version
      debug:
        msg: "{{ maven_version.stdout }}"