---
- name: Install Apache Maven 3.9.9 on Ubuntu 22.04
  hosts: all
  become: true

  vars:
    maven_version: "3.9.9"
    maven_install_dir: "/opt/maven"
    maven_download_url: "https://downloads.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"

  tasks:        

    - name: Install curl and ca-certificates
      apt:
        name:
          - curl
          - ca-certificates
          - openjdk-21-jre
        state: present
        update_cache: yes

    - name: Create Maven install directory
      file:
        path: "{{ maven_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download Maven
      get_url:
        url: "{{ maven_download_url }}"
        dest: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
        mode: '0644'

    - name: Extract Maven archive
      unarchive:
        src: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: "{{ maven_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set environment variables for Maven
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export M2_HOME={{ maven_install_dir }}
          export PATH=$M2_HOME/bin:$PATH
        mode: '0755'

    - name: Source maven.sh immediately (optional)
      shell: source /etc/profile.d/maven.sh
      args:
        executable: /bin/bash
      changed_when: false

    - name: Verify Maven version
      shell: "source /etc/profile.d/maven.sh && mvn -version"
      register: maven_version_output

    - name: Print Maven version
      debug:
        msg: "{{ maven_version_output.stdout }}"
